name: maven build
on:
  push:
    branches: [ v3 ]
  pull_request:
    branches: [ v3 ]
  workflow_dispatch:
    inputs:
      languages:
        required: true
        description: 'default language `java`'
        default: 'java'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: clean mvn
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: build maven
        run: mvn  -B clean compile
